{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2020-08-05 12:08:15,525 (util.py:66 PollingThread) ERROR - TeleBot: \"ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\\n[b\\'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}\\']',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\util.py\", line 60, in run\n",
      "    task(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\__init__.py\", line 279, in __retrieve_updates\n",
      "    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\__init__.py\", line 249, in get_updates\n",
      "    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\apihelper.py\", line 194, in get_updates\n",
      "    return _make_request(token, method_url, params=payload)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\apihelper.py\", line 60, in _make_request\n",
      "    return _check_result(method_name, result)['result']\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\apihelper.py\", line 79, in _check_result\n",
      "    raise ApiException(msg, method_name, result)\n",
      "telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n",
      "[b'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}']\n",
      "\"\n",
      "2020-08-05 12:12:06,279 (util.py:66 PollingThread) ERROR - TeleBot: \"ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\\n[b\\'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}\\']',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\util.py\", line 60, in run\n",
      "    task(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\__init__.py\", line 279, in __retrieve_updates\n",
      "    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\__init__.py\", line 249, in get_updates\n",
      "    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\apihelper.py\", line 194, in get_updates\n",
      "    return _make_request(token, method_url, params=payload)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\apihelper.py\", line 60, in _make_request\n",
      "    return _check_result(method_name, result)['result']\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\apihelper.py\", line 79, in _check_result\n",
      "    raise ApiException(msg, method_name, result)\n",
      "telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n",
      "[b'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}']\n",
      "\"\n",
      "2020-08-05 12:12:06,284 (__init__.py:420 MainThread) ERROR - TeleBot: \"A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n",
      "[b'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}']\"\n",
      "2020-08-05 12:12:09,999 (util.py:66 PollingThread) ERROR - TeleBot: \"ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\\n[b\\'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}\\']',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\util.py\", line 60, in run\n",
      "    task(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\__init__.py\", line 279, in __retrieve_updates\n",
      "    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\__init__.py\", line 249, in get_updates\n",
      "    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\apihelper.py\", line 194, in get_updates\n",
      "    return _make_request(token, method_url, params=payload)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\apihelper.py\", line 60, in _make_request\n",
      "    return _check_result(method_name, result)['result']\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\apihelper.py\", line 79, in _check_result\n",
      "    raise ApiException(msg, method_name, result)\n",
      "telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n",
      "[b'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}']\n",
      "\"\n",
      "2020-08-05 12:12:10,000 (__init__.py:420 MainThread) ERROR - TeleBot: \"A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n",
      "[b'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}']\"\n",
      "2020-08-05 12:12:14,102 (util.py:66 PollingThread) ERROR - TeleBot: \"ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\\n[b\\'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}\\']',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\util.py\", line 60, in run\n",
      "    task(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\__init__.py\", line 279, in __retrieve_updates\n",
      "    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\__init__.py\", line 249, in get_updates\n",
      "    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\apihelper.py\", line 194, in get_updates\n",
      "    return _make_request(token, method_url, params=payload)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\apihelper.py\", line 60, in _make_request\n",
      "    return _check_result(method_name, result)['result']\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\apihelper.py\", line 79, in _check_result\n",
      "    raise ApiException(msg, method_name, result)\n",
      "telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n",
      "[b'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}']\n",
      "\"\n",
      "2020-08-05 12:12:14,106 (__init__.py:420 MainThread) ERROR - TeleBot: \"A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n",
      "[b'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}']\"\n",
      "2020-08-05 12:12:19,237 (util.py:66 PollingThread) ERROR - TeleBot: \"ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\\n[b\\'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}\\']',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\util.py\", line 60, in run\n",
      "    task(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\__init__.py\", line 279, in __retrieve_updates\n",
      "    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\__init__.py\", line 249, in get_updates\n",
      "    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\apihelper.py\", line 194, in get_updates\n",
      "    return _make_request(token, method_url, params=payload)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\apihelper.py\", line 60, in _make_request\n",
      "    return _check_result(method_name, result)['result']\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\apihelper.py\", line 79, in _check_result\n",
      "    raise ApiException(msg, method_name, result)\n",
      "telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n",
      "[b'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}']\n",
      "\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2020-08-05 12:12:19,240 (__init__.py:420 MainThread) ERROR - TeleBot: \"A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n",
      "[b'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}']\"\n",
      "2020-08-05 12:12:26,618 (util.py:66 PollingThread) ERROR - TeleBot: \"ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\\n[b\\'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}\\']',)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\util.py\", line 60, in run\n",
      "    task(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\__init__.py\", line 279, in __retrieve_updates\n",
      "    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\__init__.py\", line 249, in get_updates\n",
      "    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\apihelper.py\", line 194, in get_updates\n",
      "    return _make_request(token, method_url, params=payload)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\apihelper.py\", line 60, in _make_request\n",
      "    return _check_result(method_name, result)['result']\n",
      "  File \"C:\\ProgramData\\Anaconda3\\envs\\DeepPavlovBot\\lib\\site-packages\\telebot\\apihelper.py\", line 79, in _check_result\n",
      "    raise ApiException(msg, method_name, result)\n",
      "telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n",
      "[b'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}']\n",
      "\"\n",
      "2020-08-05 12:12:26,619 (__init__.py:420 MainThread) ERROR - TeleBot: \"A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n",
      "[b'{\"ok\":false,\"error_code\":409,\"description\":\"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\"}']\"\n"
     ]
    }
   ],
   "source": [
    "'''\n",
    "Создать чат-бот для оформления заявки на потребительский кредит.\n",
    "Цель – минимизировать объем полей, заполняемых клиентом.\n",
    "Максимальное количество полей должно быть заполнено из открытых источников без нарушения Федерального закона  № 152-ФЗ «О персональных данных»\n",
    "'''\n",
    "\n",
    "import config\n",
    "import telebot\n",
    "from telebot import types  # кнопки\n",
    "from string import Template\n",
    "import telebot\n",
    "\n",
    "bot = telebot.TeleBot('1302667182:AAHMoB8cQOZReu2bjEKugEf9Q--7QFJLbi0')\n",
    "\n",
    "user_dict = {}\n",
    "\n",
    "class User:\n",
    "    def __init__(self, credit):\n",
    "        self.credit = credit\n",
    "\n",
    "        keys = ['fullname', 'phone', 'Sum','email']\n",
    "\n",
    "        for key in keys:\n",
    "            self.key = None\n",
    "\n",
    "\n",
    "# если /help, /start\n",
    "@bot.message_handler(commands=['help', 'start'])\n",
    "def send_welcome(message):\n",
    "    #markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)\n",
    "    #itembtn1 = types.KeyboardButton('/about')\n",
    "    itembtn2 = types.KeyboardButton('/reg')\n",
    "    #key = types.InlineKeyboardMarkup()\n",
    "    #markup.add(itembtn1, itembtn2)\n",
    "    #key.add(itembtn2)\n",
    "    keyboard = types.InlineKeyboardMarkup(row_)\n",
    "    keyboard.add(*[types.KeyboardButton(name) for name in ['Russian', 'English','German']])\n",
    "    \n",
    "    bot.send_message(message.chat.id, \"Здравствуйте \"\n",
    "                     + message.from_user.first_name\n",
    "                     + \",я - помощник «Россельхозбанк»!, чтобы вы хотели узнать?\", reply_markup=markup)\n",
    "    bot.send_message(message.chat.id, \"Могу рассказать вам о продуктах Банка, помогу в выборе и оформлю их за пару минут.\", reply_markup=markup)\n",
    "    bot.send_message(message.chat.id, \"P.S. Всегда можно перейти в «Главное меню» или попросить «Помощь», только напишите мне об этом!\", reply_markup=markup)\n",
    "    \n",
    "\n",
    "\n",
    "# /about\n",
    "@bot.message_handler(commands=['about'])\n",
    "def send_about(message):\n",
    "    bot.send_message(message.chat.id, \"В боте вы можете ввести свои данные для оформления завки на потребительский кредит\")\n",
    "\n",
    "\n",
    "# /reg\n",
    "@bot.message_handler(commands=[\"reg\"])\n",
    "def credit_period(message):\n",
    "    markup = types.ReplyKeyboardMarkup(one_time_keyboard=True, resize_keyboard=True)\n",
    "    itembtn1 = types.KeyboardButton('1 год')\n",
    "    itembtn2 = types.KeyboardButton('2 года')\n",
    "    itembtn3 = types.KeyboardButton('3 года')\n",
    "    itembtn4 = types.KeyboardButton('4 года')\n",
    "    itembtn5 = types.KeyboardButton('5 лет')\n",
    "    markup.add(itembtn1, itembtn2, itembtn3, itembtn4, itembtn5)\n",
    "\n",
    "    msg = bot.send_message(message.chat.id, 'Срок кредита', reply_markup=markup)\n",
    "    bot.register_next_step_handler(msg, process_period_step)\n",
    "\n",
    "\n",
    "def process_period_step(message):\n",
    "    try:\n",
    "        chat_id = message.chat.id\n",
    "        user_dict[chat_id] = User(message.text)\n",
    "\n",
    "        # удалить старую клавиатуру\n",
    "        markup = types.ReplyKeyboardRemove(selective=False)\n",
    "\n",
    "        msg = bot.send_message(chat_id, 'Фамилия Имя Отчество', reply_markup=markup)\n",
    "        bot.register_next_step_handler(msg, process_fullname_step)\n",
    "\n",
    "    except Exception as e:\n",
    "        bot.reply_to(message, 'ooops!!')\n",
    "\n",
    "\n",
    "def process_fullname_step(message):\n",
    "    try:\n",
    "        chat_id = message.chat.id\n",
    "        user = user_dict[chat_id]\n",
    "        user.fullname = message.text\n",
    "\n",
    "        msg = bot.send_message(chat_id, 'Ваш номер телефона')\n",
    "        bot.register_next_step_handler(msg, process_phone_step)\n",
    "\n",
    "    except Exception as e:\n",
    "        bot.reply_to(message, 'ooops!!')\n",
    "\n",
    "\n",
    "def process_phone_step(message):\n",
    "    try:\n",
    "        int(message.text)\n",
    "\n",
    "        chat_id = message.chat.id\n",
    "        user = user_dict[chat_id]\n",
    "        user.phone = message.text\n",
    "\n",
    "        msg = bot.send_message(chat_id, 'Сумма кредита')\n",
    "        bot.register_next_step_handler(msg, process_creditsum_step)\n",
    "\n",
    "    except Exception as e:\n",
    "        msg = bot.reply_to(message, 'Вы ввели что то другое. Пожалуйста введите номер телефона.')\n",
    "        bot.register_next_step_handler(msg, process_phone_step)\n",
    "\n",
    "\n",
    "def process_creditsum_step(message):\n",
    "    try:\n",
    "        chat_id = message.chat.id\n",
    "        user = user_dict[chat_id]\n",
    "        user.Sum = message.text\n",
    "\n",
    "        msg = bot.send_message(chat_id, 'Введите e-mail')\n",
    "        bot.register_next_step_handler(msg, process_email_step)\n",
    "\n",
    "    except Exception as e:\n",
    "        bot.reply_to(message, 'ooops!!')\n",
    "\n",
    "\n",
    "def process_email_step(message):\n",
    "    try:\n",
    "        chat_id = message.chat.id\n",
    "        user = user_dict[chat_id]\n",
    "        user.email = message.text\n",
    "\n",
    "        msg = bot.send_message(chat_id, 'День рождения\\nВ формате: День.Месяц.Год')\n",
    "        bot.register_next_step_handler(msg, process_bd_step)\n",
    "\n",
    "    except Exception as e:\n",
    "        bot.reply_to(message, 'ooops!!')\n",
    "\n",
    "def process_bd_step(message):\n",
    "    try:\n",
    "        chat_id = message.chat.id\n",
    "        user = user_dict[chat_id]\n",
    "        user.carDate = message.text\n",
    "\n",
    "        bot.send_message(chat_id, getRegData(user, 'Ваша заявка', message.from_user.first_name), parse_mode=\"Markdown\")\n",
    "    except Exception as e:\n",
    "        bot.reply_to(message, 'ooops!!')\n",
    "\n",
    "\n",
    "def getRegData(user, title, name):\n",
    "    t = Template(\n",
    "        '$title *$name* \\n Срок кредита: *$userCredit* \\n ФИО: *$fullname* \\n Телефон: *$phone* \\n Сумма: *$Sum* \\n E-mail: *$email* \\n ')\n",
    "\n",
    "    return t.substitute({\n",
    "        'title': title,\n",
    "        'name': name,\n",
    "        'userCredit': user.credit,\n",
    "        'fullname': user.fullname,\n",
    "        'phone': user.phone,\n",
    "        'Sum': user.Sum,\n",
    "        'email': user.email,\n",
    "    })\n",
    "\n",
    "\n",
    "# произвольный текст\n",
    "@bot.message_handler(content_types=[\"text\"])\n",
    "def send_help(message):\n",
    "    bot.send_message(message.chat.id, 'О нас - /about\\nРегистрация - /reg\\nПомощь - /help')\n",
    "\n",
    "\n",
    "# произвольное фото\n",
    "@bot.message_handler(content_types=[\"photo\"])\n",
    "def send_help_text(message):\n",
    "    bot.send_message(message.chat.id, 'Напишите текст')\n",
    "\n",
    "bot.enable_save_next_step_handlers(delay=2)\n",
    "\n",
    "bot.load_next_step_handlers()\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    bot.polling(none_stop=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
